version: "3.4"
services:

  wrenidm:
    image: wrenidm:latest
    container_name: wrenidm
    command: ["-p", "project"]
    depends_on:
      - openldap
      - h2database
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - type: bind
        source: ./project
        target: /opt/wrenidm/project

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    command: --loglevel debug
    ports:
      - "389:389"
      - "636:636"

    environment:
      LDAP_ORGANISATION: "Wren Security"
      LDAP_DOMAIN: "wrensecurity.org"

  h2database:
    build: ./h2-image
    container_name: h2database
    entrypoint: bash -c "java -cp /h2/h2.jar org.h2.tools.RunScript -url "jdbc:h2:~/openidm" -user openidm -password openidm -script /h2/openidm.sql && java -jar /h2/h2.jar -web -webAllowOthers -tcp -tcpAllowOthers"
    ports:
      - "8082:8082"
      - "9092:9092"
