version: "3.4"
services:

  wrenidm:
    image: ${WRENIDM_IMAGE:-wrenidm:latest}
    container_name: wrenidm
    command: ["-p", "project"]
    depends_on:
      - openldap
      - h2database
      - maildev
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - type: bind
        source: ./project
        target: /opt/wrenidm/project

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    command: --loglevel debug
    ports:
      - "389:389"
      - "636:636"

    environment:
      LDAP_ORGANISATION: "Wren Security"
      LDAP_DOMAIN: "wrensecurity.org"

  h2database:
    build: ./docker/h2
    container_name: h2database
    ports:
      - "8082:8082"
      - "9092:9092"

  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:80"
